// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides AI-powered property recommendations based on user preferences and browsing history.
 *
 * - aiPropertyRecommendations - A function that takes user preferences and browsing history as input and returns property recommendations.
 * - AIPropertyRecommendationsInput - The input type for the aiPropertyRecommendations function.
 * - AIPropertyRecommendationsOutput - The return type for the aiPropertyRecommendations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AIPropertyRecommendationsInputSchema = z.object({
  userPreferences: z
    .string()
    .describe('The user preferences for property features and location.'),
  browsingHistory: z
    .string()
    .describe('The user browsing history on the website.'),
});

type AIPropertyRecommendationsInput = z.infer<
  typeof AIPropertyRecommendationsInputSchema
>;

const AIPropertyRecommendationsOutputSchema = z.object({
  propertyRecommendations: z
    .string()
    .describe(
      'A list of recommended properties based on user preferences and browsing history.'
    ),
});

type AIPropertyRecommendationsOutput = z.infer<
  typeof AIPropertyRecommendationsOutputSchema
>;

export async function aiPropertyRecommendations(
  input: AIPropertyRecommendationsInput
): Promise<AIPropertyRecommendationsOutput> {
  return aiPropertyRecommendationsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiPropertyRecommendationsPrompt',
  input: {schema: AIPropertyRecommendationsInputSchema},
  output: {schema: AIPropertyRecommendationsOutputSchema},
  prompt: `You are an AI real estate expert. Based on the user's preferences and browsing history, recommend properties that are most relevant to their needs.

User Preferences: {{{userPreferences}}}
Browsing History: {{{browsingHistory}}}

Recommend properties:
`,
});

const aiPropertyRecommendationsFlow = ai.defineFlow(
  {
    name: 'aiPropertyRecommendationsFlow',
    inputSchema: AIPropertyRecommendationsInputSchema,
    outputSchema: AIPropertyRecommendationsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
